### ISSUE TITLE
Connection reset by peer in KitchenCI

### ISSUE THREAD

**Issue by zinefer** [schubergphilis/chef-acme#105]
I am getting the following error when trying to get a certificate for my root domain in the test kitchen:
```
================================================================================
Error executing action `create` on resource 'acme_certificate[jameskiefer.com]'
================================================================================

Faraday::ConnectionFailed
-------------------------
Connection reset by peer

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/acme/libraries/acme.rb:74:in `acme_validate_immediately'
/tmp/kitchen/cache/cookbooks/acme/resources/certificate.rb:109:in `block (2 levels) in class_from_file'
/tmp/kitchen/cache/cookbooks/acme/resources/certificate.rb:87:in `map'
/tmp/kitchen/cache/cookbooks/acme/resources/certificate.rb:87:in `block in class_from_file'
```
Here is an example of the recipe I am trying to use:
```
acme_selfsigned 'example.com' do
  crt     '/etc/ssl/example.com.crt'
  chain   '/etc/ssl/example.com-chain.crt'
  key     '/etc/ssl/example.com.key'
end

nginx_site 'example' do
  template 'nginx-static-site.conf.erb'
  variables name: 'example', domain: 'example.com', root: '/var/www/example'
  notifies :reload, 'service[nginx]', :immediately
end

directory '/var/www/example' do
  recursive true
end

acme_certificate 'example.com' do
  crt       '/etc/ssl/example.com.crt'
  chain     '/etc/ssl/example.com-chain.crt'
  key       '/etc/ssl/example.com.key'
  wwwroot   '/var/www/example'
  notifies  :reload, 'service[nginx]'
end
```

**Comment by zinefer** [comment]
Ok, I think I finally figured out what was going on. I was following the readme and looking at the code in master but my node was executing v4.0.0
