### ISSUE TITLE
Unable to activate acme-client-2.0.3, because faraday-1.0.0 conflicts with faraday (~> 0.9, >= 0.9.1)

### ISSUE THREAD

**Issue by zedtux** [schubergphilis/chef-acme#120]
I'm trying to provision new nodes with my chef repository that I used for other nodes already but it fails with the following:

```
[194.XXX.XXX.200] Recipe: acme::default
[194.XXX.XXX.200] * chef_gem[acme-client] action install
[194.XXX.XXX.200] [2020-02-28T11:49:18+00:00] INFO: Processing chef_gem[acme-client] action install (acme::default line 21)
[194.XXX.XXX.200] [2020-02-28T11:49:21+00:00] INFO: chef_gem[acme-client] installed acme-client at 2.0.3
[194.XXX.XXX.200]
[194.XXX.XXX.200] - install version 2.0.3 of package acme-client
[194.XXX.XXX.200] 
[194.XXX.XXX.200]
[194.XXX.XXX.200] 
[194.XXX.XXX.200] ================================================================================ Recipe Compile Error in /var/chef/cache/cookbooks/teleport-le/recipes/default.rb
[194.XXX.XXX.200] ================================================================================
[194.XXX.XXX.200] 
[194.XXX.XXX.200]
[194.XXX.XXX.200] Gem::ConflictError
[194.XXX.XXX.200]
[194.XXX.XXX.200] ------------------
[194.XXX.XXX.200]
[194.XXX.XXX.200] Unable to activate acme-client-2.0.3, because faraday-1.0.0 conflicts with faraday (~> 0.9, >= 0.9.1)
[194.XXX.XXX.200]
[194.XXX.XXX.200] 
[194.XXX.XXX.200]
[194.XXX.XXX.200] Cookbook Trace:
[194.XXX.XXX.200]
[194.XXX.XXX.200] ---------------
[194.XXX.XXX.200]
[194.XXX.XXX.200] /var/chef/cache/cookbooks/acme/recipes/default.rb:27:in `from_file' 
[194.XXX.XXX.200] /var/chef/cache/cookbooks/teleport-le/recipes/default.rb:54:in `from_file'
[194.XXX.XXX.200]
[194.XXX.XXX.200] 
[194.XXX.XXX.200]
[194.XXX.XXX.200] Relevant File Content:
[194.XXX.XXX.200]
[194.XXX.XXX.200] ----------------------
[194.XXX.XXX.200]
[194.XXX.XXX.200] /var/chef/cache/cookbooks/acme/recipes/default.rb: 
[194.XXX.XXX.200] 
[194.XXX.XXX.200] 20: 
[194.XXX.XXX.200] 21: chef_gem 'acme-client' do 
[194.XXX.XXX.200] 22: action :install 
[194.XXX.XXX.200] 23: version node['acme']['gem_version'] 
[194.XXX.XXX.200] 24: compile_time true if respond_to?(:compile_time) 
[194.XXX.XXX.200] 25: end 
[194.XXX.XXX.200] 26: 
[194.XXX.XXX.200] 27>> require 'acme-client' 
[194.XXX.XXX.200] 28: 
[194.XXX.XXX.200]
[194.XXX.XXX.200] 
[194.XXX.XXX.200]
[194.XXX.XXX.200] System Info:
[194.XXX.XXX.200]
[194.XXX.XXX.200] ------------
[194.XXX.XXX.200]
[194.XXX.XXX.200] chef_version=15.8.23 
[194.XXX.XXX.200] platform=debian 
[194.XXX.XXX.200] platform_version=9 
[194.XXX.XXX.200]
[194.XXX.XXX.200] ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux] 
[194.XXX.XXX.200] program_name=/usr/bin/chef-client 
[194.XXX.XXX.200] executable=/opt/chef/bin/chef-client
[194.XXX.XXX.200]
[194.XXX.XXX.200] 
[194.XXX.XXX.200]
[194.XXX.XXX.200] 
[194.XXX.XXX.200]
[194.XXX.XXX.200] Running handlers:
[194.XXX.XXX.200] [2020-02-28T11:49:21+00:00] ERROR: Running exception handlers
[194.XXX.XXX.200]
[194.XXX.XXX.200] Running handlers complete 
[194.XXX.XXX.200] [2020-02-28T11:49:21+00:00] ERROR: Exception handlers complete
[194.XXX.XXX.200]
[194.XXX.XXX.200] Chef Infra Client failed. 1 resources updated in 12 seconds
```

_P.S: `teleport-le` is a cookbook of ours which uses this cookbook, you can see its source code [here](https://gitlab.com/pharmony/teleport-le-cookbook/)_

The installed Chef version 15.8.23 seem to have installed `faraday` 1.0.0 because when I uninstall that gem version, then `chef-client` fails stating the `faraday` gem version 1.0.0 is missing while version 0.17.5 is present.

So that make me thinking this cookbook is no more compatible with Chef and needs to have the faraday dependency updated.

**Comment by gothick** [comment]
If it's relevant, there's [already an issue on the acme-client gem](https://github.com/unixcharles/acme-client/issues/178) to bump up the version of Faraday.

**Comment by zedtux** [comment]
Awesome, thank you @gothick for pointing to this issue :+1:

**Comment by zedtux** [comment]
Meanwhile, a workaround is to use Chef 15.7.32 which still uses faraday 0.17.3.
