### ISSUE TITLE
Error creating new order :: Cannot issue for "": Domain name is empty

### ISSUE THREAD

**Issue by ljapena** [schubergphilis/chef-acme#122]
Relevant software and versions

- chef-client: 13.9.4
- acme cookbook: ~> 4.1.1

When I ran my cookbooks, it failed with the following error:
`================================================================================
    Error executing action `create` on resource 'acme_certificate[*******.com.ar]'
    ================================================================================

    Acme::Client::Error::RejectedIdentifier
    ---------------------------------------
    Error creating new order :: Cannot issue for "": Domain name is empty

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/acme/libraries/acme.rb:47:in `acme_order_certs_for'
    /var/chef/cache/cookbooks/acme/resources/certificate.rb:76:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/AppLoadBalancer-acmev2/recipes/lb_reverse_proxy.rb

    157:   acme_certificate host['server_name'] do
    158:     crt     "#{node['AppLoadBalancer']['cert_path']}/#{host['server_name']}.crt"
    159:     #Se deshabilita por la nueva version de la receta de ACME - AP 20200514
    160:     #chain   "#{node['AppLoadBalancer']['cert_path']}/#{host['server_name']}-chain.crt"
    161:     key     "#{node['AppLoadBalancer']['cert_path']}/#{host['server_name']}.key"
    162:     wwwroot '/var/lib/haproxy'
    163:     alt_names ["#{host['server_alias']}"]
    164:     owner node['AppLoadBalancer']['haproxy']['user']
    165:     group node['AppLoadBalancer']['haproxy']['group']
    166:     only_if { host['balancer']['https'] }
    167:   end
    168:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/AppLoadBalancer-acmev2/recipes/lb_reverse_proxy.rb:157:in `block in from_file'

    acme_certificate("*******.com.ar") do
      action [:create]
      default_guard_interpreter :default
      declared_type :acme_certificate
      cookbook_name "AppLoadBalancer-acmev2"
      recipe_name "lb_reverse_proxy"
      crt "/etc/ssl/lojack/*******.com.ar.crt"
      key "/etc/ssl/lojack/*******.com.ar.key"
      wwwroot "/var/lib/haproxy"
      alt_names [""]
      owner "haproxy"
      group "haproxy"
      cn "*******.com.ar"
      only_if { #code block }
    end`

Site name was replaced with ******* for confidentiality purpose.

**Comment by ljapena** [comment]
Line 163 was misspelled... my bad
