### ISSUE TITLE
 Unable to activate acme-client-2.0.5, because faraday-1.4.3 conflicts with faraday (~> 0.9, >= 0.9.1)

### ISSUE THREAD

**Issue by KTM25** [schubergphilis/chef-acme#135]
Gem::ConflictError
  ------------------
  Unable to activate acme-client-2.0.5, because faraday-1.4.3 conflicts with faraday (~> 0.9, >= 0.9.1)

  Cookbook Trace: (most recent call first)
  ----------------------------------------
    /var/chef/cache/cookbooks/acme/recipes/default.rb:27:in `from_file'
    /var/chef/cache/cookbooks/smart-webserver/recipes/default.rb:18:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/acme/recipes/default.rb:

   20:
   21:  chef_gem 'acme-client' do
   22:    action :install
   23:    version node['acme']['gem_version']
   24:    compile_time true if respond_to?(:compile_time)
   25:  end
   26:
   27>> require 'acme-client'
   28:

  System Info:
  ------------
  chef_version=17.6.15
  platform=ubuntu
  platform_version=18.04
  ruby=ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
  program_name=/usr/bin/chef-client
  executable=/opt/chef/bin/chef-client

I also tried a newer version of chef-client and the issue still seems to exist. Does anyone know how far back I need to go with chef-client where this isn't an issue?

**Comment by KTM25** [comment]
Solved the issue. I went to https://rubygems.org/gems/acme-client/versions and looked through the versions to find the faraday dependency that matched what came with chef-workstation using `chef gem list faraday`. Once you have that, set your version in the gem file or as I did, in the metadata.rb 

`gem 'acme-client', '= version'`
