### ISSUE TITLE
Undeclared dependency on nginx cookbook

### ISSUE THREAD

**Issue by yardinicwaller** [schubergphilis/chef-acme#82]
This cookbook appears to (justifiably) depend on the [nginx](https://supermarket.chef.io/cookbooks/nginx) cookbook, but this is not listed in the dependencies. Attempting to use the `acme_ssl_certificate` resource without having a compatible `nginx` cookbook in the Chef run results in an error like this one.

```
[2017-07-27T19:27:31+00:00] INFO: Setting up verification...

================================================================================
Error executing action `create` on resource 'acme_ssl_certificate[/etc/ssl/mysite.com.crt]'
================================================================================

NoMethodError
-------------
No resource or method named `nginx_site' for `Chef::Provider::SSLCertificate::Nginx ""'

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/acme/libraries/ssl_certificate/nginx.rb:52:in `setup_challanges'
/tmp/kitchen/cache/cookbooks/acme/libraries/ssl_certificate.rb:105:in `block (3 levels) in action_create'
/tmp/kitchen/cache/cookbooks/acme/libraries/ssl_certificate.rb:105:in `block (2 levels) in action_create'
/tmp/kitchen/cache/cookbooks/acme/libraries/ssl_certificate.rb:91:in `map'
/tmp/kitchen/cache/cookbooks/acme/libraries/ssl_certificate.rb:91:in `block in action_create'
/tmp/kitchen/cache/cookbooks/acme/libraries/ssl_certificate.rb:90:in `action_create'
```

It seems like this should be stated in the dependencies.

**Comment by thoutenbos** [comment]
The dependency is only needed when using the ssl_certificate validation method (tlssni) in combination with the nginx webserver. In other use cases the nginx cookbook is not needed, hence no hard dependency in the metadata.
