### ISSUE TITLE
Load Error: cannot load such file -- acme-client

### ISSUE THREAD

**Issue by finferflu** [schubergphilis/chef-acme#94]
I am using:

Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13

And I get the following error with ChefSpec:

```
      LoadError:
        cannot load such file -- acme-client
      # /var/folders/2j/k1y8bp_53xz84ss2y5wn337w0000gp/T/chefspec20180313-89745-13lh3hofile_cache_path/cookbooks/acme/recipes/default.rb:27:in `from_file'
      # /var/folders/2j/k1y8bp_53xz84ss2y5wn337w0000gp/T/chefspec20180313-89745-13lh3hofile_cache_path/cookbooks/mail-processor/recipes/default.rb:113:in `from_file'
      # ./spec/unit/recipes/default_spec.rb:37:in `block (3 levels) in <top (required)>'
      # ./spec/unit/recipes/default_spec.rb:154:in `block (3 levels) in <top (required)>'
```

Am I missing something?

Thank you.

**Comment by moodwrench** [comment]
Did you ever find an answer to this?   I am hitting the same issue in my chefspec

**Comment by moodwrench** [comment]
Add the acme-client gem to your Gemfile
