### ISSUE TITLE
unknown keyword: endpoint

### ISSUE THREAD

**Issue by bcg62** [schubergphilis/chef-acme#99]
Im trying to use a custom end point and keep seeing the following:

```
    ArgumentError
    -------------
    unknown keyword: endpoint

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/acme/libraries/acme.rb:36:in `new'
    /var/chef/cache/cookbooks/acme/libraries/acme.rb:36:in `acme_client'
    /var/chef/cache/cookbooks/acme/libraries/acme.rb:48:in `acme_authz_for'
    /var/chef/cache/cookbooks/acme/resources/certificate.rb:88:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/acme/resources/certificate.rb:87:in `map'
    /var/chef/cache/cookbooks/acme/resources/certificate.rb:87:in `block in class_from_file'
```

Ive tried setting it in the acme_certificate block and also as a node attribute.

**Comment by thoutenbos** [comment]
Please try again with the latest version
